const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the wines below

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/winelist", {useNewUrlParser: true}
);

const itemSeed = [
  {
    name: "Brian's Red",
    category: "Red",
    varietal: "Pinot Noir",
    origin: "North America",
    country: "USA",
    region: "Pennslyvania",
    price: 10.89,
    inventory: 144,
    description:
      "An uplifting red wine from the Lehigh Valley. On the nose red-currant, molasses and wild sage, with hints of bramble and mint on the finish. ",
    photo: "",
    date: new Date(Date.now()),
  },
  {
    name: "Jarrod's White",
    category: "White",
    varietal: "Riesling",
    origin: "Oceania",
    country: "Australia",
    region: "McLaren Vale",
    price: 14.49,
    inventory: 144,
    description:
      "From the land of ownunder comes a high acid wine for any occasion. Pair with hard cheeses and bocce ball on warm Spring afternoon.",
    photo: "",
    date: new Date(Date.now()),
  },
  {
    name: "Alex's Rosé",
    category: "Rose",
    varietal: "Gamay",
    origin: "Europe",
    country: "France",
    region: "Burgundy",
    price: 11.29,
    inventory: 144,
    description:
      "This is Alex's secret Rosé stash that he shares only on exceptional vintages. Get ready to be 'wowed' with this gem.",
    photo: "",
    date: new Date(Date.now()),
  },
  {
    name: "Guimaro Riberia Sacra Tinto",
    category: "Red",
    varietal: "Mencia",
    origin: "Europe",
    country: "Spain",
    region: "Galicia",
    price: 18.49,
    inventory: 144,
    description:
      "From multiple plots of Mencía vines with an average age of 40 years old, located in and around Ribeira Sacra. The un-oaked, regional tinto is all about immediate pleasure with pure, lush red fruits, spices, and slate-laden minerality.  A wine to pair with all kinds of foods, especially chorizos, embutidos, roast pork, spicy foods, any dish with a lot of Pimentón. ",
    photo: "guimaro",
    date: new Date(Date.now()),
  },
  {
    name: "Subliminal Santa Barbara Cabernet Sauvignon",
    category: "Red",
    varietal: "Cabernet Sauvignon",
    origin: "North America",
    country: "USA",
    region: "California",
    price: 22.39,
    inventory: 144,
    description:
      "Subliminal is a partnership between the Parientes (Nomadic Distribution) and the Porters (Amplify Wines).  Born out of a shared desire to capture a style of Cabernet Sauvignon almost forgotten in California- that of a humble table wine- Subliminal is a weeknight wine that speaks strongly of its origins.  Its dusty tannin and dried fruit recall 1970s California, while its bright, fresh, lifted character is a purely modern take on the grape.  From old vines in the Santa Ynez Valley planted over 40 years ago, aged completely in neutral oak, with no additions other than a minimum of sulfur dioxide, this is a new side of California Cabernet Sauvignon that will carry you from summer BBQs to winter braises.",
    photo: "subliminal",
    date: new Date(Date.now()),
  },
  {
    name: "Siete Rioja Joven",
    category: "Red",
    varietal: "Grenache",
    origin: "Europe",
    country: "Spain",
    region: "Rioja",
    price: 11.59,
    inventory: 144,
    description: "Ole",
    photo: "siete",
    date: new Date(Date.now()),
  },
  {
    name: "Enderle & Moll Pinot Noir",
    category: "Red",
    varietal: "Pinot Noir",
    origin: "Europe",
    country: "Germany",
    region: "Baden",
    price: 16.59,
    inventory: 144,
    description: "rot is gut",
    photo: "enderle",
    date: new Date(Date.now()),
  },
  {
    name: "Château La Grolet",
    category: "Red",
    varietal: "Merlot",
    origin: "Europe",
    country: "France",
    region: "Bordeaux",
    price: 17.49,
    inventory: 144,
    description: "Classic",
    photo: "grolet",
    date: new Date(Date.now()),
  },
  {
    name: "Benoît Roseau Syrah de Rosette",
    category: "Red",
    varietal: "Syrah",
    origin: "Europe",
    country: "France",
    region: "Rhone",
    price: 17.29,
    inventory: 144,
    description: "Iconic",
    photo: "benoit",
    date: new Date(Date.now()),
  },
  {
    name: "Mary Taylor (Filipe Ferreira) Douro Tinto",
    category: "Red",
    varietal: "Tinta Roriz",
    origin: "Europe",
    country: "Portugal",
    region: "Douro",
    price: 14.09,
    inventory: 144,
    description: "Steep grade",
    photo: "douro",
    date: new Date(Date.now()),
  },
  {
    name: "Piollot Champagne Les Protelles Rosé Extra Brut",
    category: "Sparkling",
    varietal: "Pinot Noir",
    origin: "Europe",
    country: "France",
    region: "Champagne",
    price: 58.99,
    inventory: 144,
    description: "Bubbly",
    photo: "piollot",
    date: new Date(Date.now()),
  },
  {
    name: "Domaine Nerantzi Koniaros PGI Serres",
    category: "Red",
    varietal: "Koniaros",
    origin: "Europe",
    country: "Greece",
    region: "Macedonia",
    price: 69.19,
    inventory: 144,
    description: "What is this?",
    photo: "nerantzi",
    date: new Date(Date.now()),
  },
  {
    name: "Domaine des Gandines Mâcon-Péronne",
    category: "White",
    varietal: "Chardonnay",
    origin: "Europe",
    country: "France",
    region: "Burgundy",
    price: 16.39,
    inventory: 144,
    description: "Dangerous",
    photo: "gandines",
    date: new Date(Date.now()),
  },
  {
    name: "Campo Mendoza Malbec",
    category: "Red",
    varietal: "Malbec",
    origin: "South America",
    country: "Argentina",
    region: "Mendoza",
    price: 10.99,
    inventory: 144,
    description: "Whatever",
    photo: "campo",
    date: new Date(Date.now()),
  },
  {
    name: "Escándalo Valle de Colchagua Sémillon",
    category: "White",
    varietal: "Semillon",
    origin: "South America",
    country: "Chile",
    region: "Colchagua Valley",
    price: 17.29,
    inventory: 144,
    description: "Clandestine",
    photo: "escandalo",
    date: new Date(Date.now()),
  },
  {
    name: "Bichi Tecate La Gorda Yori (Skin contact)",
    category: "Orange",
    varietal: "Palomino",
    origin: "North America",
    country: "Mexico",
    region: "Baja California",
    price: 26.09,
    inventory: 144,
    description:
      "The nose is of dried apricot and pear. Nectar with slate minerality on the second sip. Almost medicinal but not unpleasantly so. A real natural expression of the Tecate terroir",
    photo: "bichi",
    date: new Date(Date.now()),
  },
  {
    name: "Mirco Mariotti Fortana dell'Emilia Rosato 'Sèt e Mèz'",
    category: "Rosé",
    varietal: "Fortana",
    origin: "Europe",
    country: "Italy",
    region: "Emilia-Romagna",
    price: 19.99,
    inventory: 144,
    description:
      "This is made from a rare red called Fortana – a savoury wild thing with high acid and a black cherry or wild strawberry notes depending on vintage; it also has a bitter vermouth-like spice to it. I find it similar to the Lambrusco di Sorbara, with a less refined acidity but a more a savory complexity. Yes, please!",
    photo: "setemez",
    date: new Date(Date.now()),
  },
  {
    name: "Migliarina Montozzi Chianti Superiore",
    category: "Red",
    varietal: "Sangiovese",
    origin: "Europe",
    country: "Italy",
    region: "Tuscany",
    price: 17.29,
    inventory: 144,
    description: "Take home to mother",
    photo: "montozzi",
    date: new Date(Date.now()),
  },
  {
    name: "Serata Prosecco",
    category: "Sparkling",
    varietal: "Glera",
    origin: "Europe",
    country: "Italy",
    region: "Veneto",
    price: 17.29,
    inventory: 144,
    description: "Good morning",
    photo: "serata",
    date: new Date(Date.now()),
  },
];

db.Item
  .remove({})
  .then(() => db.Item.collection.insertMany(itemSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
